@echo off
rem "awstats data file" | "Web Server Statistics" | "Usage Statistics" | pagecounter | pagevisits | "Generated by Webalizer" | "Summary Period"
rem "193.173.48.34" inurl: "awstats" | "awstats" | inurl:"Web Server Statistics for" | "Usage Statistics for" | intitle:pagecounter | intitle:"pagevisits on" | "Generated by Webalizer" | "Summary Period"
rem | "Summary Period"
rem awstats | inurl:"statistics for" | intitle:pagecounter | intitle:"pagevisits on" | "Generated by Webalizer" 
rem intitle:"Statistics for" |  awstats | intitle:pagecounter | intitle:"pagevisits on" | "Generated by Webalizer" | "Summary Period" | "web server"

"c:\Program Files (x86)\Mozilla Firefox\firefox.exe" -new-window
timeout /t 3

start "" "https://www.google.nl/search?num=100&newwindow=1&q=%%22%1%%22"
timeout /t 10
start "" "https://www.google.nl/search?num=100&newwindow=1&q=%%22%1%%22+intitle%%3A%%22Statistics+for%%22+%%7C++awstats+%%7C+intitle%%3Apagecounter+%%7C+intitle%%3A%%22pagevisits+on%%22+%%7C+%%22Generated+by+Webalizer%%22+%%7C+%%22Summary+Period%%22+%%7C+%%22web+server%%22+%%7C++inurl:%%22LiveReport.aspx?id=%%22+|+%%22log%%22+|+%%22irc%%22+|+%%22channel%%22"
timeout /t 10
start "" "https://www.google.nl/search?num=100&newwindow=1&q=%%22%1%%22+inurl%%3A%%22open%%3Bcsv.last%%22+|+intitle%%3Abelstat+|intitle%%3A%%22Usage+statistics%%22|intext%%3A%%22If+you+remove+this+file%%2C+all+statistics+for+date%%22"
timeout /t 10
start "" "https://www.google.nl/search?num=100&newwindow=1&q=%%22%1%%22+spam+|report+|blacklist|%%22abuse+report%%22+|attack"

REM Test met 145.15.244.26 (NS wifi in de trein)
